//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppTestServico.servicoCRM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaCRMSoap", Namespace="http://mrv.com.br/ConsultaCRM")]
    public partial class ConsultaCRM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ObterInformacaoBlocoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarUnidadeSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarAgendamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaCRM() {
            this.Url = global::AppTestServico.Properties.Settings.Default.TodoListDaemonWithCert_servicoCRM_ConsultaCRM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterInformacaoBlocoCompletedEventHandler ObterInformacaoBlocoCompleted;
        
        /// <remarks/>
        public event ValidarUnidadeSAPCompletedEventHandler ValidarUnidadeSAPCompleted;
        
        /// <remarks/>
        public event CancelarAgendamentoCompletedEventHandler CancelarAgendamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mrv.com.br/ConsultaCRM/ObterInformacaoBloco", RequestNamespace="http://mrv.com.br/ConsultaCRM", ResponseNamespace="http://mrv.com.br/ConsultaCRM", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BlocoInfoSAP[] ObterInformacaoBloco() {
            object[] results = this.Invoke("ObterInformacaoBloco", new object[0]);
            return ((BlocoInfoSAP[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterInformacaoBlocoAsync() {
            this.ObterInformacaoBlocoAsync(null);
        }
        
        /// <remarks/>
        public void ObterInformacaoBlocoAsync(object userState) {
            if ((this.ObterInformacaoBlocoOperationCompleted == null)) {
                this.ObterInformacaoBlocoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterInformacaoBlocoOperationCompleted);
            }
            this.InvokeAsync("ObterInformacaoBloco", new object[0], this.ObterInformacaoBlocoOperationCompleted, userState);
        }
        
        private void OnObterInformacaoBlocoOperationCompleted(object arg) {
            if ((this.ObterInformacaoBlocoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterInformacaoBlocoCompleted(this, new ObterInformacaoBlocoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mrv.com.br/ConsultaCRM/ValidarUnidadeSAP", RequestNamespace="http://mrv.com.br/ConsultaCRM", ResponseNamespace="http://mrv.com.br/ConsultaCRM", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarUnidadeSAP(string idUnidade) {
            object[] results = this.Invoke("ValidarUnidadeSAP", new object[] {
                        idUnidade});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarUnidadeSAPAsync(string idUnidade) {
            this.ValidarUnidadeSAPAsync(idUnidade, null);
        }
        
        /// <remarks/>
        public void ValidarUnidadeSAPAsync(string idUnidade, object userState) {
            if ((this.ValidarUnidadeSAPOperationCompleted == null)) {
                this.ValidarUnidadeSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarUnidadeSAPOperationCompleted);
            }
            this.InvokeAsync("ValidarUnidadeSAP", new object[] {
                        idUnidade}, this.ValidarUnidadeSAPOperationCompleted, userState);
        }
        
        private void OnValidarUnidadeSAPOperationCompleted(object arg) {
            if ((this.ValidarUnidadeSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarUnidadeSAPCompleted(this, new ValidarUnidadeSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mrv.com.br/ConsultaCRM/CancelarAgendamento", RequestNamespace="http://mrv.com.br/ConsultaCRM", ResponseNamespace="http://mrv.com.br/ConsultaCRM", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelarAgendamento(string oportundiadeId) {
            this.Invoke("CancelarAgendamento", new object[] {
                        oportundiadeId});
        }
        
        /// <remarks/>
        public void CancelarAgendamentoAsync(string oportundiadeId) {
            this.CancelarAgendamentoAsync(oportundiadeId, null);
        }
        
        /// <remarks/>
        public void CancelarAgendamentoAsync(string oportundiadeId, object userState) {
            if ((this.CancelarAgendamentoOperationCompleted == null)) {
                this.CancelarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("CancelarAgendamento", new object[] {
                        oportundiadeId}, this.CancelarAgendamentoOperationCompleted, userState);
        }
        
        private void OnCancelarAgendamentoOperationCompleted(object arg) {
            if ((this.CancelarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mrv.com.br/ConsultaCRM")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://mrv.com.br/ConsultaCRM", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mrv.com.br/ConsultaCRM")]
    public partial class BlocoInfoSAP {
        
        private string nomeField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObterInformacaoBlocoCompletedEventHandler(object sender, ObterInformacaoBlocoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterInformacaoBlocoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterInformacaoBlocoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlocoInfoSAP[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlocoInfoSAP[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ValidarUnidadeSAPCompletedEventHandler(object sender, ValidarUnidadeSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarUnidadeSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarUnidadeSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591